version: "3.9"

services:
  # PHP-FPM Service (Laravel)
  app:
    build: .
    volumes:
      - ./:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - laravel-network
    depends_on:
      - db
      - redis

  # Nginx Service
  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network

  # Redis Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - laravel-network

# Networks and Volumes
volumes:
  db_data:
    driver: local

networks:
  laravel-network:
    driver: bridge
